
title: Tutorials Corner
email: less.tact_0m@icloud.com
description: Practical examples for pipelines I have written, and tutorials for common workflows in plant biology research. 
url: "https://teashull.github.io"
github_username:  TeaShull
baseurl: "" # the subpath of your site, e.g. /blog
url: " https://teashull.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: jekyll/minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark